name: container_name

services:
  backend:
    container_name: container_name
    image: image_name
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: "postgresql+asyncpg://postgres:password@db:5432/dbname"
      PASSWORD_SECRET: supersecret
      JWT_SECRET: supersecret
      JWT_ALORITHM: HS256
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SENDER_EMAIL: super_email
      SENDER_PASSWORD: supersecret
      OTHER_DB_PASSWORD: Mukangwiz112
      OTHER_HOST: other host url
      OTHER_PORT: 3306
      OTHER_USER: user
      OTHER_PASSWORD: supersecret
      OTHER_DB_URL: "mysql+asyncmy://user:password@superhost:3306/dbname"

  db:
    container_name: container_name
    image: postgres:latest #MYSQL, POSTGRES, etc...
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: db_name
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
